### ISSUE TITLE
Avro serializer for Kafka

### ISSUE THREAD

**Issue by beto580** [zarusz/SlimMessageBus#11]
Currently Avro serialization is not supported.
We need to add this plugin in addition to the existing Json serializer.
https://www.nuget.org/packages/Apache.Avro/

**Comment by zarusz** [comment]
The initial prototype is ready and available as a beta build:
https://www.nuget.org/packages/SlimMessageBus.Host.Serialization.Avro

The branch is here if you wish to add a sample or modify that: https://github.com/zarusz/SlimMessageBus/tree/feature/avro_serializer

There is no sample yet nor has that been tested. I just want to make sure conceptually it could work for you - I am open to feedback.

You would use it with the existing sample as with the JSON serializer. The class AvroMessageSerializer would be used instead and it has few essential properties:
* WriteSchemaLookup
* ReadSchemaLookup

These are simply Func's that lookup the avro schema object used while when writing and reading form wire. I was thinking if not to make them like a dictionary object per each Type, but then the Func should be more flexible as you can load the schema dynamically.

There are other properties you could customize, but they are less essential.

Let's chat on gitter.

**Comment by zarusz** [comment]
The Avro plugin based on the Apache.Avro has been released: https://www.nuget.org/packages/SlimMessageBus.Host.Serialization.Avro/1.0.0

Please reopen if you find any issues.

**Comment by beto580** [comment]
Thanks for all the help @zarusz , it was an enriching experience working with you. I hope we can contribute more in the future. Until next time!

**Comment by zarusz** [comment]
Glad things worked out @beto580. Take care!
