### ISSUE TITLE
[Host.AzureMessageBus] Subscription was not created.

### ISSUE THREAD

**Issue by baoduy** [zarusz/SlimMessageBus#117]
Hi @zarusz 
Seems there is a bug the subscription was not created when the TopologyProvisioning is like below

```csharp
TopologyProvisioning = new ServiceBusTopologyProvisioningSettings
{
        Enabled = true,
        CanConsumerCreateQueue = false,
        CanConsumerCreateTopic = false,
        CanProducerCreateTopic = false,
        CanProducerCreateQueue = false,
        CanConsumerCreateSubscription = true,
}
```

However, It is working fine when the TopologyProvisioning is
```csharp
TopologyProvisioning = new ServiceBusTopologyProvisioningSettings
{
        Enabled = true,
        CanConsumerCreateSubscription = true,
}
```

The reason is I would like to allow the applications to create subscriptions only and all other topics, Infra will manage service bus creation. Is there something I'm missing?

Thanks
Steven

**Comment by zarusz** [comment]
Hey @baoduy,

I believe that this would be a bug/edge case. In particular, I iterate over topics to be created, and if this is not enabled, then I do not iterate over subscriptions (it's an inner loop).  Let me address it later today, and issue a patch build.

**Comment by zarusz** [comment]
Hey @baoduy another RC is available for you check: https://www.nuget.org/packages/SlimMessageBus.Host.AzureServiceBus/1.19.1-rc2

I have tested and it does work in those edge cases now. 
Additionally, when queue//topic/subscription/rule create is not allowed but SMB detects it is missing it will emit a warning in the logs.

Let me know and if no further issues, I would like to release the 1.19.1

**Comment by baoduy** [comment]
Hi @zarusz I have tested and this one works well in [1.19.1-rc2](https://www.nuget.org/packages/SlimMessageBus.Host.AzureServiceBus/1.19.1-rc2) released.

Thanks
Steven
