### ISSUE TITLE
IConsumer as a message loop (Consumer without the IConsumer<T> interface)

### ISSUE THREAD

**Issue by unruledboy** [zarusz/SlimMessageBus#12]
Hi,

Currently IConsumer is used as an interface, and message received through OnHandle function.

In scenarios like a infinite loop, it makes more sense to register a handler like IReceiverClient from Microsoft.Azure.ServiceBus.Core which process incoming messages in a local function, which can fit into the scanario I mentioned.

```
receiverClient.RegisterMessageHandler<FooMessageType>((message, token) => 
{
    //process the message here
});
```

**Comment by zarusz** [comment]
Hi @unruledboy would something like the below work for you?

```cs
IMessageBus messageBus = MessageBusBuilder
	.Create()
	// Pub/Sub example
	.Produce<AddCommand>(x => x.DefaultTopic(topicForAddCommand))
	.Consume<AddCommand>(x => x
		.Topic(topicForAddCommand)
		.WithConsumer((message, name) => {
			Console.WriteLine("Processing message...");
			return Task.Delay(1000);
		})
        // ...
	)
    // ...
    .Build();
```

The `WithConsumer()` could come in two flavors:
* `Func<TMessage, string, Task>` - the string is the queue/topic/path name (depending on your transport)
* `Func<TMessage, Task>`

Passing a CancellationToken is not yet supported (it would have to be a new feature).

With this it could be transport provider agnostic and should work for all currently supported plugins.

Let me know.

**Comment by unruledboy** [comment]
@zarusz  aha! This should be, but there are boilerplate codes required upfront.

Would be it possible just to have a normal DI to get an instance of IMessageBus and start processing the message?

**Comment by zarusz** [comment]
You can register the IMessageBus into your DI and then inject whenever you need. However, it would give you methods to publish/send message only.

I am not super clear about the ask. Beyond the proposed snipped. 
Are you asking about being able to subscribe at runtime to different topics (or reconfigure at runtime)? Or are you asking about making the fluent config API a bit condensed?

Perhaps you could share a snippet.

**Comment by unruledboy** [comment]
Hi,

Let me explain a bit further, as you proposed, I will have to have the real-life code like this:
```

public class FooMessageProcessor
{
private IMessageBus messageBus;

public void Start()
{
       messageBus = MessageBusBuilder
	.Create()
	// Pub/Sub example
	.Produce<AddCommand>(x => x.DefaultTopic(topicForAddCommand))
	.Consume<AddCommand>(x => x
		.Topic(topicForAddCommand)
		.WithConsumer((message, name) => {
			Process(message, name)
		})
        // ...
	)
    // ...
    .Build();
}

private void Process(FooMessage message, string name)
{

}

}

```

**Comment by zarusz** [comment]
What you're describing would be an ability to:
* Allow for consumer registration after the bus is created (at runtime)

There are couple of challenges with that approach when I thought about it a while ago...
Also, not sure what that would solve for.



With the current version, you need to declare all the producers and consumers at the bus creation (using the fluent builder API). Internally it does cache the configuration, build lookup/routing and transport native clients. Please note SMB is not only about InMemory provider.

So currently your `FooMessageProcessor` needs to implement the `IConsumer<FooMessageType>`.  Then register your `FooMessageProcessor` in the DI.

```cs
public class FooMessageProcessor
{
private IMessageBus messageBus;

public FooMessageProcessor(IMessageBus messageBus)
{ 
  this.messageBus = messageBus;
}


public void Start()
{
   //some other logics
}

public Task OnHandle(FooMessage message, string name)
{
  this.messageBus.Publish(new AnotherMessage());
}

}
```

I hope the other issue around lifecycle shed some light on this.

**Comment by zarusz** [comment]
@unruledboy I thought about this a bit and did some prototyping. 

On one hand I want to separate the bus configuration (MessageBusBuilder.Create()...Build()) at app startup from the runtime (when messages are flowing in). This has to do that certain registrations have to happen before on providers other than Memory (mostly performance considerations). 
On top of that, I prefer to have the similar config experience across different transport providers, so any new API change has to be considerate about all these.

Now, what I was able to prototype and have almost working across all providers:
* You no longer have to implement the `IConsumer<T>` interface in your consumer.
* There will be two more overloads for `.WithConsumer<>()`:

``` cs
// bus configuration
.Consume<FooMessage >(x => x
	// the usual, you need to implement IConsumer<FooMessage> in FooMessageProcessor
	.WithConsumer<FooMessageProcessor>() 
	// or, a method name which is expected to be Task Arrived(FooMessage, string) on the FooMessageProcessor is expected, no need to implement IConsumer, the method can be private
	.WithConsumer<FooMessageProcessor>(nameof(FooMessageProcessor.Arrived))
	// or, same as above, but using strongly typed Expression<Func<TConsumer, TMessage, string, Task>>, the method has to be public
	.WithConsumer<FooMessageProcessor>((consumer, message, name) => consumer.Arrived(message, name))
)
```

Still the `FooMessageProcessor` has to be registered in the DI, so that SMB can ask DI to resolve it. The `FooMessageProcessor` lifecycle is up to your DI setup.

Here is how your processor would look like:

```cs
public class FooMessageProcessor
{
	public IAsyncEnumerable<FooModel> Feed(CancellationToken cancellationToken)
	{
	   //some other logics here
	   var queue = new  ConcurrentQueue<FooModel>();
	   var resetEvent = new AutoResetEvent(false);

	  // I know it looks odd here, but the whole purpose was to have a long running loop that constantly return the changes back to the consumer via the new IAsyncEnumerable<T> feature.
	  while(true)
	  {
		 cancellationToken.ThrowIfCancellationRequested();
		 while (queue.TryDequeue(out var result))
		 {
			 yield return result;
		 }
		  resetEvent.WaitOne();
	   }
	}

	// SMB delivers messages here, I could make the name parameter optional...
	private async Task Arrived(FooMessage message, string name)
	{
		queue.Enqueue(Process(message, name));
		resetEvent.Set();        
	}

	private FooModel Process(FooMessage message, string name)
	{
	   //some logic here
	   return new FooModel(xxx);
	}
}
```

Would that work better for you?

**Comment by unruledboy** [comment]
@zarusz  that looks way better, and quite interesting. I wonder what the performance will look like, this should be done by reflection, right?

**Comment by zarusz** [comment]
@unruledboy the 1st method `.WithConsumer<FooMessageProcessor>()`  is the fastest as it will be an interface method call (`IConsumer.OnHandle()`).

The 2nd approach will be pure reflection `.WithConsumer<FooMessageProcessor>(nameof(FooMessageProcessor.Arrived))`, so it will be the slowest. That said, I do cache the method lookup ([MethodInfo](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo?view=netstandard-2.0).

The 3rd approach will use [Expression<>.Compile()](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=netstandard-2.0), so the speed will be in between 1st and 2nd. That said, I think I do not need to use the Expression<Func<>> and will turn to using Func<> directly. 

I shall push a branch for this soon. Also will add relevant code documentation with performance annotation. That said, either way the slowest will be IO and serialization.

**Comment by zarusz** [comment]
The RC version for SMB.Host.Memory with the additional config methods  is available on nuget:
https://www.nuget.org/packages/SlimMessageBus.Host.Memory/1.4.0-rc1

Please give it a try and report if any issues.
Cheers

**Comment by unruledboy** [comment]
@zarusz sorry for the delay.

It says does not contains definition of .Consumer(xxx)

![image](https://user-images.githubusercontent.com/682883/73491327-7dd5ac00-4402-11ea-86ca-d5de73d8397b.png)

**Comment by zarusz** [comment]
@unruledboy you need to add the `.Topic(...)` before the `.WithConsumer(...)` as in here:
https://github.com/zarusz/SlimMessageBus/blob/develop/src/Samples/Sample.DomainEvents.WebApi/Startup.cs#L100
https://github.com/zarusz/SlimMessageBus/blob/develop/src/Samples/Sample.Simple.ConsoleApp/Program.cs#L103

**Comment by zarusz** [comment]
This is now released since: 
https://www.nuget.org/packages/SlimMessageBus.Host.Memory/1.4.0

Also available across all the other transport providers.

**Comment by unruledboy** [comment]
@zarusz  very nice and simple API. You could promote the project like writing a series of blog articles
