### ISSUE TITLE
Winforms

### ISSUE THREAD

**Issue by MohMehrnia** [zarusz/SlimMessageBus#121]
How Do Used in Winforms?

**Comment by zarusz** [comment]
Hey, what version of .net and winforms are you using? What DI library do you use?

Is haven't used winforms in years, but looking at this it should be possible to use with SlimMessageBus.

https://stackoverflow.com/questions/70475830/how-to-use-dependency-injection-in-winforms

**Comment by zarusz** [comment]
hey @MohMehrnia, is this still an issue? Do you have further questions?
