### ISSUE TITLE
SlimMessageBus.Host.Serialization.Json  still required even it is not used

### ISSUE THREAD

**Issue by unruledboy** [zarusz/SlimMessageBus#13]
Hi,

In my case( in-memory host), I set EnableMessageSerialization is false, it is still required to install and configure the SlimMessageBus.Host.Serialization.Json.

Is it possible not to force the usage of the serialization?

**Comment by zarusz** [comment]
Hello, 

Just to clarify if you do not configure any serializer (e.g. SlimMessageBus.Host.Serialization.Json) and set the `EnableMessageSerialization = false` on the InMemory provider the SMB throws and configuration exception?

Here is the suspect:
https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host/MessageBusBase.cs#L56

**Comment by unruledboy** [comment]
@zarusz  precisely! I think it would be better not to throw exception.

**Comment by zarusz** [comment]
It should be fixed since v1.3.2.
https://www.nuget.org/packages/SlimMessageBus.Host.Memory/1.3.2
