### ISSUE TITLE
[Host.Redis] Error logged every time while processing redi pub/sub topic

### ISSUE THREAD

**Issue by Frizlee** [zarusz/SlimMessageBus#140]
Error "Error occured while processing the redis pub/sub topic {Topic}" is logged every time even if there is no actual exception. 
It seems like a bug in RedisTopicConsumer.cs class.

**Comment by zarusz** [comment]
Hello @Frizlee , thanks for the report. What version do you use?
I will look into this.

**Comment by zarusz** [comment]
@Frizlee the fix is ready on this version https://www.nuget.org/packages/SlimMessageBus.Host.Redis/1.22.1

Try it out and once confirmed that it works please close this issue.

**Comment by zarusz** [comment]
@Frizlee any feedback on this?

**Comment by Frizlee** [comment]
Hi @zarusz, we just tested the new version 1.22.1 and it seems that everything works as expected. Thanks!
