### ISSUE TITLE
Update Host.Kafka to use Confluent.Kafka client v1.x

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#15]
The Confluent.Kafka client was redesigned from version 1.x:
https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Client#version-011x-vs-1x

The 1.x introduced breaking changes.
We need to upgrade SMB to use the latest client.

**Comment by snowroller** [comment]
hi, has the development started for this issue?

**Comment by zarusz** [comment]
hey @MagnusNiv01 I did an initial check how big the changes are in the underlying client, however nothing more than that. My plan is to complete the migration before end of this year. People have been asking about that too.

**Comment by narve** [comment]
Any update on this issue?

**Comment by zarusz** [comment]
I have a WIP branch on my local (still doesn't compile). There are quite some changes when migrating from 0.x to latest 1.5.3.
My current thinking is that a release of SMB Kafka should happen sometime closer to end of February.
I might have an RC version available for testing in early Feb.

**Comment by zarusz** [comment]
Hi, The first version of Kafka transport plugin upgraded to latest Confluent client is available to try out:
https://www.nuget.org/packages/SlimMessageBus.Host.Kafka/1.11.0-rc1

Please have a look, and report here any issues.

**Comment by zarusz** [comment]
The Kafka transport provider based on latest Confluent.Kafka client has been released:
https://www.nuget.org/packages/SlimMessageBus.Host.Kafka/1.11.0
