### ISSUE TITLE
[Host.RabbitMq] Multiple consumers with varying concurrency

### ISSUE THREAD

**Issue by robert94p** [zarusz/SlimMessageBus#205]
how to process messages in parallel when using RabbitMq?

**Comment by zarusz** [comment]
hello @robert94p ,

By default, the underlying RabbitMq net driver uses a concurrency of 1.
Following [this](https://www.rabbitmq.com/dotnet-api-guide.html#consumer-callbacks-and-ordering) it can be adjusted on the `ConnectionFactory` object.

For example, try to set this via SMB like so:

```cs
services.AddSlimMessageBus((mbb) =>
{
    mbb.WithProviderRabbitMQ(cfg =>
    {
        cfg.ConnectionFactory.ConsumerDispatchConcurrency = 2; // default is 1
        // ...
    }
}
```

Please let me know if this worked for you.

**Comment by robert94p** [comment]
registered several buses for one consumer. While it works

**Comment by zarusz** [comment]
Did you try the provided suggestion (with `ConsumerDispatchConcurrency` setting)?
Sounds like you've taken another route, can you explain what you mean several buses for one consumer?
Thanks

**Comment by zarusz** [comment]
As part of #207 I have updated the docs to include information on how to increase concurrency.

If you run into any problems, please re-open the issue and let me know.

Thanks!

**Comment by zarusz** [comment]
Moving the following from @robert94p https://github.com/zarusz/SlimMessageBus/issues/310#issuecomment-2543040984:

```
Apologies, I wrote this under the wrong issue; it should have been under https://github.com/zarusz/SlimMessageBus/issues/205

I need 2 or more consumers. I have one producer, one exchange, and three queues for three different consumers. When publishing a message, the target queue is determined via the routingKey.

One of the consumers performs a resource-intensive operation, so it needs to be limited to processing only 2 messages in parallel. The other consumers can handle more messages simultaneously.

I would like to configure the number of messages that can be processed concurrently per consumer, similar to how it works in MemoryMessageBus. Currently, messages are processed based on the ConsumerDispatchConcurrency setting, which applies globally to all consumers.
```

**Comment by zarusz** [comment]
@robert94p I believe this is a good example of what you are trying to achieve, correct?
https://www.rabbitmq.com/tutorials/tutorial-four-dotnet

Here is the preview release to try out:
https://www.nuget.org/packages/SlimMessageBus.Host.RabbitMQ/2.6.2-rc10

Here is a pseudo sample:

```csharp
services.AddSlimMessageBus(mbb => 
{
  mbb.Produce<PingMessage>(x => x
        .Exchange("exchange", exchangeType: ExchangeType.Direct)
        .RoutingKeyProvider((m, p) => m.Label));

  // messages with blue routing key will get 1 concurrency
  mbb.Consume<PingMessage>(x => x
      .Queue("queue", autoDelete: false)
      .ExchangeBinding("orders", routingKey: "blue")
      .Instances(1));

  // messages with red routing key will get 1 concurrency
  mbb.Consume<PingMessage>(x => x
      .Queue("queue", autoDelete: false)
      .ExchangeBinding("orders", routingKey: "red") 
      .Instances(10));  
});
```

Let me know if that works for you.

**Comment by zarusz** [comment]
I just pushed a refined version:
https://www.nuget.org/packages/SlimMessageBus.Host.RabbitMQ/2.6.2-rc12

With that, the overall concurrency should be improved.
