### ISSUE TITLE
[Host.RabbitMQ] Automatically ack messages 

### ISSUE THREAD

**Issue by robert94p** [zarusz/SlimMessageBus#214]
How to ack messages automatically? so that a message started for processing is not processed again when the service is restarted

**Comment by zarusz** [comment]
So if I understand, you'd like to Ack the message right away upon arrival (before even processing starts in case the service process dies)? This will lead to at-most-once delivery guarantees. 

There is no direct way to make it happen nowadays, there is something similar that lets the user decide if to Ack or Nack in case of an error (see [here](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_rabbitmq.md#custom-consumer-error-handler)).

What I could propose is to 1) add a custom [interceptor](https://github.com/zarusz/SlimMessageBus/blob/master/docs/intro.md#generic-interceptors) and 2) a way to Ack imperatively in that interceptor before message processing. The 2) will require a new feature which I could add here quite soon. The interceptor example is below:

```cs
public class AckConsumerInterceptor<TMessage> : IConsumerInterceptor<TMessage>
{
   public async Task<object> OnHandle(TMessage message, Func<Task<object>> next, IConsumerContext context) 
   {
      context.Ack(); // ack before message processing starts (at-most-once)
      return await next(); // process the message
   }
}
```

Let me know if that works.

**Comment by robert94p** [comment]
Thank you,  works

**Comment by robert94p** [comment]
I was wrong,  don't work context.Ack()
Error
`System.Collections.Generic.KeyNotFoundException: The given key 'RabbitMq_MessageConfirmAction' was not present in the dictionary. `

**Comment by robert94p** [comment]
Сall context.Ack() in consumer handler throws an error
`System.Collections.Generic.KeyNotFoundException: The given key 'RabbitMq_MessageConfirmAction' was not present in the dictionary.  `

**Comment by zarusz** [comment]
@robert94p as I wrote earlier `he 2) will require a new feature which I could add here quite soon.`. Once I add the feature it will be available for you to use. Are you in a hurry on this?

**Comment by zarusz** [comment]
@robert94p thinking about it some more:
* it would be best to give a setting to have automated acks at the beginning (this is what you want) or at the end (currently works like that) of message processing.
* in addition give the user the power to perform context.Ack() or contextNack() when there is more involved logic - as in my earlier example

That way we can avoid the interceptor altogether.

Let me know what you think.

**Comment by zarusz** [comment]
Great, that's what I am working on now.

**Comment by zarusz** [comment]
hey @robert94p the feature is in preview as of version 2.3.0-rc1: https://www.nuget.org/packages/SlimMessageBus.Host.RabbitMQ

More about the feature:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_rabbitmq.md#acknowledgment-mode

You should be able to set the [`AckAutomaticByRabbit `](https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqMessageAcknowledgementMode.cs).
