### ISSUE TITLE
Hybrid Could not find route

### ISSUE THREAD

**Issue by nikes** [zarusz/SlimMessageBus#22]
Not correct typeof 
![image](https://user-images.githubusercontent.com/1352682/77853556-4d857080-71ed-11ea-82cb-51c47d44f9e0.png)

**Comment by zarusz** [comment]
Can you please share a bit more details on:
* How do you call the `bus.Send<T>(T msg)`? Do you pass the `IRequestMessage<PlayerReconnectRespoins>` as `T?
* Your hybrid bus setup around registering the request messages?

**Comment by nikes** [comment]
1. call _bus.Send(new PlayerReconnectRequest())
2. yeap, i registred producer at hybrid bus
```
.Produce<PlayerReconnectRequest>(x => x.DefaultTopic(x.Settings.MessageType.Name))
```

```
public class PlayerReconnectRequest : IRequestMessage<PlayerReconnectResponse>
{
}
```

**Comment by nikes** [comment]
@zarusz try change here https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs#L95
to 
```
var messageType = message.GetType();
```

**Comment by zarusz** [comment]
Yes, you're right @nikes.

Can you please check if version 1.7.3 works for you?

https://www.nuget.org/packages/SlimMessageBus.Host.Hybrid/1.7.3

**Comment by nikes** [comment]
Test 1.7.3 Work
Thx
