### ISSUE TITLE
Missing MaxAutoRenewDuration on Azure Service Bus implementation

### ISSUE THREAD

**Issue by tomaszzmuda** [zarusz/SlimMessageBus#23]
Hi @zarusz

I'm looking for a way to change the default MaxAutoRenewDuration parameter. On Azure ServiceBus message is visible again after 5 minutes if the user doesn't mark it as completed manually. 
We have a case that processing on a single message could take up to 2 hours. Right now by handle that passing MaxAutoRenewDuration parameter to [MessageHandlerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.messagehandleroptions?view=azure-dotnet). 

Unfortunately, [BaseConsumer](https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.AzureServiceBus/Consumer/BaseConsumer.cs) does not set this method. 

Is there any method that we can use to achieve the same result?
Or maybe can we made a pull request with changes (but probably you will have to tell us how do you see that).

**Comment by s-krawczyk** [comment]
+1

**Comment by zarusz** [comment]
Hey guys, 

We could add a SB provider specific [consumer setting](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_azure_servicebus.md#consuming-messages) like the below on the consumer registration:

```cs
mbb.Consume<TMessage>(x => x
    .Topic("some-topic")
    .WithConsumer<TConsumer>()
    .SubscriptionName($"subscriber-name")
    .Instances(1))
    .MaxAutoRenewDuration(TimeSpan.FromHours(2)); // <----- here
```

That setting would be applied for that `TMessage` consumer only. 

I think it would also make sense to add a bus wide (shared across all SB consumers) setting like the following:

```cs
MessageBusBuilder mbb = MessageBusBuilder
    .Create()
    // the bus configuration here
    .WithProviderServiceBus(new ServiceBusMessageBusSettings(connectionString) {
       MaxAutoRenewDuration = TimeSpan.FromHours(2) // <----- here
    })
    .WithSerializer(new JsonMessageSerializer());

IMessageBus bus = mbb.Build();
```

Would that meet your needs?
If so, I can make a quick patch and expose this as an RC release for you to try out.

**Comment by zarusz** [comment]
See the https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_azure_servicebus.md#transport-specific-settings
