### ISSUE TITLE
Azure Service Bus questions

### ISSUE THREAD

**Issue by s-krawczyk** [zarusz/SlimMessageBus#24]
Hi, would like to ask for few things:

1. How to configure it to use with situation where different types of events are sent to the same topic and I would like to have one subscription. Reason is to have order of messages around one aggregate. Is this possible?

1.  Is it possible to configure serialization based on some header from message? Like I don't want to use type.Name because in case someone change type name everything will fail. And as we know people are often changing names during refactor. I prefer to have some const with type ma to which deserialize it. What you think?

2. There is some idea to support Azure Service Bus sessions? Now it fails.

At the end very, very good code. I don't remember when last time I have seen such high quality repository! 

Thumb up! For you!

**Comment by zarusz** [comment]
Hi @s-krawczyk,

I will try to respond quickly now to get you going, but will need to reflect on some of these a bit more later.

Re 1
Do these message types share a base class or are they totally unrelated? 
What serialization do yo use?

SMB supports polymophic messages (they have to share the same ancestry). Examples here:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/intro.md#polymorphic-messages

The consumer side would register for the base type. In your IConsumer<BaseType> you'd have to check which type of concrete message it is (instanceof or sth) and delegate handling to your respective app logic.

It's important to note that the underlying serialization has to support polymorphic types (e.g. Json.NET $type discriminator).

If your messages are unrelated, then it its not supported by SMB, and specyfically the serializer would have a difficulty of knowing. It could be possible with some `IMessageSerializer` customization, but it's not something supported out of the box atm. Not sure if it would make sense to be honest.

Re 2. 
I was thinking about it at some point. This could be added as a feature. It looks like it's related with your ask (1). What serialization are you using? Can you share message examples?

Re 3.

**Comment by zarusz** [comment]
Feel free to reopen if you need further clarification or open another feature request.
