### ISSUE TITLE
$Default rule is not added to subscription

### ISSUE THREAD

**Issue by winiarski91** [zarusz/SlimMessageBus#254]
After upgrading from version 2.2.3 to 2.3.3, we observed that the $Default rule is not being added to the subscription, leading to messages not being consumed from ASB.

**Comment by zarusz** [comment]
Might be related to changes in #245.

**Comment by EtherZa** [comment]
> Might be related to changes in #245.

It appears to be the case. #245 changed the flow to always delete the default rule regardless of whether there was a replacement rule or not.

PR #255 realigns the code base with the original workflow.

**Comment by zarusz** [comment]
Thanks @EtherZa. I will have a look at your PR. Also started to look at it now - wanted to add more integration tests around cleaning of existing ASB topology in the tests, so that we can capture such in the future.

**Comment by zarusz** [comment]
Fixed in version [2.3.4](https://www.nuget.org/packages/SlimMessageBus.Host.AzureServiceBus/2.3.4)
