### ISSUE TITLE
[Integration tests] Move parts of the integration test infra to Test Containers hosted by GitHub runners

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#277]
Provision an Azure-hosted VM to run containers for the build pipeline (integration tests).

Also soon the CloudKarafka hosting is coming to [end of its life](https://www.cloudkarafka.com/blog/end-of-life-announcement.html) and we need to find a Kafka hosting replacement.
We could simply run Test Containers instead.

**Comment by EtherZa** [comment]
@zarusz FYI: GitHub hosted runners come with Docker pre-installed.

[GitHub sample](https://github.com/peter-evans/docker-compose-actions-workflow)
[TestContainers](https://dotnet.testcontainers.org/cicd/)

**Comment by zarusz** [comment]
Thanks for the find. When I read I got the impression the default runners don't support docker.

**Comment by zarusz** [comment]
Closed via #278 minus the caveat that Kafka will be moved to Test Containers after #110.
