### ISSUE TITLE
[Host.Nats] Transport for Nats.io

### ISSUE THREAD

**Issue by damien-blanchet** [zarusz/SlimMessageBus#286]
Hello,

I would like to propose the support of Nats.io. 

I looked into using MQTT, which is already supported by SlimMessageBus and Nats, but Nats only supports MQTT 3.1 at the moment and this prevents the use of the Request-Reply functionality which depends on the headers available in MQTT 5.

https://nats.io/
https://github.com/nats-io/nats.net/tree/main

**Comment by zarusz** [comment]
Hi @damien-blanchet ,

I never heard of Nats, but it looks fresh and modern.

Are you looking to contribute a new transport called `SlimMessageBus.Host.Nats` or are you asking if maintainers could build it?
Going only with MQTT protocol might not leverage all the intrinsic features of Nats (besides the one you mention the MQTT 3.1 and lack of headers).

**Comment by damien-blanchet** [comment]
Hi @zarusz, I am looking to contribute to a new transport called SlimMessageBus.Host.Nats

**Comment by zarusz** [comment]
Cool, let me know if you need any pointers.
 
I'd suggest copying one of the simpler transports (Mqtt, Redis) and starting from there.
Also, be sure to provide an integration test (see any ones ending with `It`) and leverage test containers.

**Comment by dblanchetatlectra** [comment]
I've opened a PR with the Nats transport implementation I'm proposing, largely inspired by the MQTT transport implementation.

However, I have a problem with the execution of integration tests: the nats_endpoint variable is not found, even though I think I've set it correctly as an environment variable. Any idea what's going wrong?

**Comment by zarusz** [comment]
Great, let's discuss the int test issues over in the PR. I can see what's going on and comment there.

**Comment by zarusz** [comment]
Closed via #287
