### ISSUE TITLE
[Host.Outbox] Execute permission is required for Outbox

### ISSUE THREAD

**Issue by zzeneg** [zarusz/SlimMessageBus#297]
Hey,

When trying to use Outbox feature, we receive the following error: `The EXECUTE permission was denied on the object 'OutboxId', database 'SQL-DB-SAMPLE', schema 'dbo'.` 

My understanding that EXEC permission is required for the custom `OutboxId` type, and that error could be fixed with something like `GRANT EXEC ON TYPE::[dbo].[OutboxId] TO [User]` but it's an issue to get such permission in secured environments and I wonder if it's possible to use Outbox without the custom type.

Thanks!

**Comment by zarusz** [comment]
Ok, we will try to see if we custom type can be avoided to relax the permission needs.

**Comment by zarusz** [comment]
@zzeneg could you try it and report here if it worked for you?
https://www.nuget.org/packages/SlimMessageBus.Host.Outbox.DbContext/2.5.2-rc1

The custom type was removed, so hopefully the EXEC permission should not be needed.

**Comment by zzeneg** [comment]
I tried `2.5.2-rc1` - it seems to work. No custom type, no issues with permissions :) Thanks!

**Comment by zarusz** [comment]
Released in:
https://www.nuget.org/packages/SlimMessageBus.Host.Outbox.DbContext/2.5.2
https://www.nuget.org/packages/SlimMessageBus.Host.Outbox.DbContext/3.0.0-rc10
