### ISSUE TITLE
Port to .NET Standard 2.x

### ISSUE THREAD

**Issue by jfritchman** [zarusz/SlimMessageBus#3]
Are there any plans to port SlimMessageBus to .NET Standard?

**Comment by zarusz** [comment]
Yes, there are plans. Recently I have even started the work. Right now I am not sure how long will this take, but should not be as much problematic to do (watch out for a feature branch).

In terms of version, my goal is to target the lowest .NET Standard whenever possible, as this will give most coverage for users.

**Comment by jfritchman** [comment]
Thanks for the update
