### ISSUE TITLE
How to cancel a long-running task in a consumer

### ISSUE THREAD

**Issue by robert94p** [zarusz/SlimMessageBus#328]
There is a service that receives a request to an endpoint via rest. Upon receiving the request, the service assigns a task ID and sends the request to a message bus using SlimMessageBus. This task will be processed by a consumer in the background. The consumer may be within the current service or in a different service. How can this task be canceled after some time upon receiving a separate request to the service?

**Comment by zarusz** [comment]
I would need to understand this more to help here. How many bus transports are you using and in what way (in memory, out of process Rabbit, default sync Publish on memory bus, request-response over message bus)?

In general these could help
- for request-response you have a way to specify timeout for the response to arrive (see timeout param of the Send method)
- there is a CancellationToken that could be passed in both publish/send but that would work on within the same process only (if you need to cancel the processing when the rest request is canceled)
- the consumer in v3 accepts the CancellationToken in the OnHandle method or implementing IConsumerContextAware in v2.

Let me know.

**Comment by robert94p** [comment]
I use several services that involve different message buses, both in-memory and external to the RabbitMQ process, operating in publish mode. When working within a single process, it’s straightforward to implement cancellation by passing a CancellationToken and caching the CancellationTokenSource. Upon receiving a rest request for cancellation, I can retrieve the corresponding CancellationTokenSource and cancel the task.

However, I encounter challenges when working in a separate process through RabbitMQ. Before trying to invent my own solution, I wanted to ask if there’s already an existing solution that I could use for this.

**Comment by robert94p** [comment]
Thank you, I was thinking about a solution like that too.

**Comment by zarusz** [comment]
@robert94p let's close the issue unless there is more that we need to discuss here or there is a need to create some feature.
