### ISSUE TITLE
In Memory Bus Count

### ISSUE THREAD

**Issue by t11omas** [zarusz/SlimMessageBus#334]
Is there any way to see/monitor the count of messages on the in memory bus?  (might be another example of a good metric to log)

We have a process that reads a lot of data and places it onto an in memory bus to be processed.  It would be nice to be able to see/monitor that in memory bus

**Comment by zarusz** [comment]
Please lets carry on in #333 and close this one.

**Comment by t11omas** [comment]
That is fine, i didn't want to have multiple questions/feature requests as part of one ticket, but will close for now
