### ISSUE TITLE
[Host.AzureServiceBus] Correlation filters

### ISSUE THREAD

**Issue by EtherZa** [zarusz/SlimMessageBus#349]
Add support for correlation filters with Azure Service Bus.

"Complex filter rules require processing capacity. In particular, the use of SQL filter rules cause lower overall message throughput at the subscription, topic, and namespace level. Whenever possible, applications should choose correlation filters over SQL-like filters because they're much more efficient in processing and have less impact on throughput." - [Correlation filters](https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters#correlation-filters)

**Comment by zarusz** [comment]
Closed via: #350 350
