### ISSUE TITLE
Support for scoped Consumers

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#35]
In some cases the consumer (`IConsumer<T>`) needs to inject scoped dependencies (like the EF DbContext) hence needs to be registered as scoped in the DI container. As a result, the SMB should create a scope and resolve such consumers in that scoped container. The scope should be bound to each message which represents a transaction or a unit of work.

Also related to #34 .

**Comment by nover** [comment]
I'm currently playing around with this library to get a feeling of it on a project. I had a scoped consumer registered which basically stalled the whole publish/work/wait flow with the last log being:
`The service XYZEventHandler will be requested from the app scope` and then nothing happened, and the calling thread got blocked infinitely.

This is pretty unfortunate for newcomers like me :) Also because your sample `WebApi` actually register the `OrderSubmittedHandler` as `Scoped` so I was expecting this to work (see here: https://github.com/zarusz/SlimMessageBus/blob/master/src/Samples/Sample.DomainEvents.WebApi/Startup.cs)

Anyway, +1 from here for supporting scoped handlers.

**Comment by sorenlorentzen** [comment]
I am in the exact same situation as @nover.

I really need scoped consumers

**Comment by nover** [comment]
@zarusz I've been playing around - could the solution be as simple as this in the `AspNetCoreMessageBusDependencyResolver.Resolve` method ?

```
public object Resolve(Type type)
        {
            IServiceProvider currentServiceProvider;

            // When the call to resolve the given type is made within an HTTP Request, use the request scope service provider
            var httpContext = _httpContextAccessor?.HttpContext;
            if (httpContext != null)
            {
                _logger.LogDebug("The service {0} will be requested from the per-request scope", type);
                currentServiceProvider = httpContext.RequestServices;
                return currentServiceProvider.GetService(type);
            }

            // otherwise use the app wide scope provider
            _logger.LogDebug("The service {0} will be requested from the app scope", type);
            using (var serviceScope = _serviceProvider.CreateScope())
            {
                currentServiceProvider = serviceScope.ServiceProvider;
                return currentServiceProvider.GetService(type);
            }
        }
```

**Comment by sorenlorentzen** [comment]
Having played around with this for some time now, I actually managed to have everything work as intended.  
I am not sure what went wrong as I have deleted my old code.

I have all my consumers derive from `BaseEventHandler<T>` which in turn implements `IConsumer<T>` where `T` is the event I'm consuming.  

On application startup I'm using reflection to find all types inheriting from BaseEventHandler.

```
private class HandlerEventPair
{
    public Type HandlerType { get; set; }
    public Type EventType { get; set; }
}
```

```
var _typePairs = allTypes
    .Where(x => x.BaseType != null)
    .Where(x => x.BaseType.IsGenericType)
    .Where(x => x.BaseType.IsAbstract)
    .Where(x => x.BaseType.GetGenericTypeDefinition() == typeof(BaseEventHandler<>))
    .Select(x => new HandlerEventPair
    {
        HandlerType = x,
        EventType = x.BaseType.GenericTypeArguments.First(),
    }).ToArray();
```

and finally I'm calling `Produce` and `Consume` for each pair.

```
services.AddScoped<IMessageBus>(x =>
{
    var mbb = MessageBusBuilder
        .Create()
        .WithProviderMemory(new MemoryMessageBusSettings
        {
            EnableMessageSerialization = false
        })
        .WithDependencyResolver(new AspNetCoreMessageBusDependencyResolver(x));

    foreach(var typePair in _typePairs)
    {
        mbb.Produce(typePair.EventType, x => x.DefaultTopic(x.Settings.MessageType.Name));
        mbb.Consume(typePair.EventType, x => x.Topic(x.MessageType.Name).WithConsumer(typePair.HandlerType));
    }

    return mbb.Build();
});

foreach(var typePair in _typePairs)
{
    services.AddScoped(typePair.HandlerType);
}
```

I'm sorry for the messy code. It's all I could manage in the time I had!

**Comment by zarusz** [comment]
Hey guys, 

The issue here is that scoped consumers it would need to work for all transports. 

InMemory is rather an easy one - because in conjunction with `AspNetCoreMessageBusDependencyResolver` and registering the handler as `Scoped` it should work in the Http Request context. Now, the DomainEvents sample works (for me at least) @nover , so you might be running into a bug or something - it would be good if you could post your setup.

To your sample above @nover the scope is getting disposed too soon (if no HTTP context).
On my commercial project (where I use SMB) for Azure SB we did implement a base consumer that combines both of your ideas @nover  and @sorenlorentzen . 
The difference is that the `ScopedConsumer<T> : IConsumer<T>` acts as a decorator to the target consumer which is marked as `Scoped` and the `using (var serviceScope = _serviceProvider.CreateScope())` is inside the Consumer method of the ScopedConsumer but then there was also a tweak to the IDependencyResolver to tap into the current scope. Effectively this gives a per-message scope which I guess is the ask of this issue.

My plan is to have that replicated into the SMB library across all transports. The thing is that it would have to be tested and documented which eats up time ;)

**Comment by nover** [comment]
I totally get that this is a complicated matter, also due to the other DI libraries that SMB supports :)

My setup on a high level is the following:

- Aspnet core 5.0 WebApi
- Scoped background worker that runs a WebSocket client to consume events from an external system. Each "handler" for different message types are executed as separate threads on the thread-pool
- Then I want those handlers to be able to send domain events to the platform (which is a monolith now to de-complicate some matters), thus using the InMemory provider
- I experience the lockups in the background service worker when emitting the events.

Right now I have circumvented the problem by registering a whole lot of things as Singleton, but I would prefer them to be Scoped.

When i get a bit of time I can try to make a minimal repro of the setup to give you something to debug from.

> Effectively this gives a per-message scope which I guess is the ask of this issue.

Exactly, spot on :)

Anyway thanks for this awesome library.

**Comment by zarusz** [comment]
@nover I looked at your use case and thought a bit about your setup. I don't think this would be a bug in SMB...

In general I think after the `The service XYZEventHandler will be requested from the app scope` the handler lookup likely fails because your background thread has no HttpContext.Current and so (see [AspNetCoreMessageBusDependencyResolver](https://github.com/zarusz/SlimMessageBus/blob/461c279be8ddc38856af1e98121f98059e63701b/src/SlimMessageBus.Host.AspNetCore/AspNetCoreMessageBusDependencyResolver.cs#L50)) it fails because it falls back to the root container which has no scope and so the handler is registered as a scoped handler on the DI which cannot be created on the root container (likely an exception is thrown),

Now, I  believe this could work for your use case:
1. Create a scope for each of the web socket frame/request/message (`using (var serviceScope = _serviceProvider.CreateScope())` - bound to the one web socket massage.
2. Have Some `ScopeHolder` class that has `AsyncLocal<IServiceProvider>` inside that you set just after the scope service provider is created
3. Provide your own `IDependencyResolver` implementation from SMB that work like `AspNetCoreMessageBusDependencyResolver` but use the `ScopeHolder.Current` rather than `HttpContect.Current`

That could work I think.
Let me know if that brings you anywhere. 

The above suggestion and code classes will likely be present in the `SlimMessageBus.Host` nuget once I complete this feature.
Just that the fluent config would hide it all nicely for a good dev experience...

**Comment by zarusz** [comment]
Hello, the feature has been implemented.

Any feedback on the proposed will be much appreciated!

A preview is available on nuget:
https://www.nuget.org/packages/SlimMessageBus.Host/1.12.0-rc1
https://www.nuget.org/packages/SlimMessageBus.Host.Kafka/1.12.0-rc1
https://www.nuget.org/packages/SlimMessageBus.Host.AzureServiceBus/1.12.0-rc1
https://www.nuget.org/packages/SlimMessageBus.Host.Redis/1.12.0-rc1

The docs are here:
https://github.com/zarusz/SlimMessageBus/blob/feature/scoped_consumers/docs/intro.md#per-message-di-container-scope
https://github.com/zarusz/SlimMessageBus/blob/feature/scoped_consumers/docs/provider_memory.md#per-message-di-scope
