### ISSUE TITLE
[Host.AzureServiceBus] Ability to auto generate topology (queue/topic/subscription) in Azure Service Bus

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#38]
There should be an option (or another plugin) added to `Host.AzureServiceBus` plugin that would generate a topic (with the relevant subscruption) or queue if it does not exist yet.

The information about the topology could be read from the queue / topic / subscriptions registered within the SMB (on the producer and consumer side). 

Ideally some additional options should be made available that would affect the topic/queue attributes (partitioning enabled, duplicate detection, etc).

It should be an opt-in feature.

**Comment by GMillerVarian** [comment]
Would this feature provide the ability for multiple instances of the same service to each receive a copy of all messages? With Redis, this is already possible because each service instance is an independent subscriber. We are looking for a way to get the same behavior using ASB, but currently it doesn't seem like this is possible - or is it?

**Comment by zarusz** [comment]
No, this feature request is strictly to be able to create the topology in ASB (queues/topics/subscriptions) automatically if they don't exist in ASB. Perhaps this feature could somewhat solve your problem, but let me first digress here...

Redis is very specific in how it implements the pub/sub as stated in the first paragraph [here](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_redis.md#pubsub) each Redis client instance is its own subscriber for a Redis topic.

In contrast, for a topic ASB requires each consumer instance to provide the subscription name from which the service instance will be consuming. Technically in order for all of your service instances to get the same copy, each instance would have to create its own subscription (at runtime, or as part of config)  - `SubscriptionName_{ProcessId| OR NodeName OR SomeIndex}`.

Potentially, if this feature to create topology would be implemented, you could:
- Let SMB create these subscriptions during the service instance start 
- Make these subscriptions get autodeleted (ASB feature) after some period of inactivity (2 days) especially if your instances come and go. This depends on your use case.
