### ISSUE TITLE
Reflective registration of producers/consumers in samples seem off

### ISSUE THREAD

**Issue by nover** [zarusz/SlimMessageBus#40]
I'm trying to use the `.Do(...)` reflective registration of producers and consumers as outlined in the samples repository of the WebApi: https://github.com/zarusz/SlimMessageBus/blob/master/src/Samples/Sample.DomainEvents.WebApi/Startup.cs#L98

However, when I use this registration method for my one sample producer/consumer, the following is logged:
```
[20:01:35 DBG] Found a base type of Namespace.XyzEvent that is configured in the bus: System.Object
```
Seems to me like the sample is missing the following piece of code down in the `.ForEach(find => ..)` method:
```
  builder.Produce(find.EventType,
                            x => x.DefaultTopic(x.Settings.MessageType.Name));
```

I'll happily contribute an PR fixing it if you agree :)

**Comment by zarusz** [comment]
Hi @nover , yes I agree. Happy to get a PR from you ;)
