### ISSUE TITLE
pub/sub with just one consumer / queue communication in redis transport

### ISSUE THREAD

**Issue by fbonjour81** [zarusz/SlimMessageBus#45]
Is there any way to publish a message and be handled by just one consumer? the message is something like a task, I am using redis as provider, it has a command RPOPLPUSH that do what I want but not sure if I can use it with this lib. thanks

**Comment by zarusz** [comment]
Hello @fbonjour81 ,

Using pub/sub every consumer will get a copy of the message. We'd need to use a queue. 

Currently the lib has redis pub/sub implemented. However to have a reliable queue support we'd have to extend the redis transport plugin to leverage commands as you pointed out: 
https://redis.io/commands/RPOPLPUSH


I am happy to look into this and add queue implementation to the redis transport to make it more powerful. We have that for example with Azure Service Bus transport already.

Now,  is that something you can wait for or are you considering other libs at the moment? In general it should be an easy addition.

**Comment by fbonjour81** [comment]
I can wait, I am already using Hangfire for in-process background tasks and I think it allows to separate the client from server using queues. So I would use SMB for event/notification messages and Hangfire for tasks.

Let me know if you implement this feature in some moment. 
Thanks

**Comment by zarusz** [comment]
Hi @fbonjour81, the queue implementation for Redis is released here if you want to try it:
https://www.nuget.org/packages/SlimMessageBus.Host.Redis/1.13.0-rc1

The docs are here:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_redis.md

Please let me know what you think. Cheers.
