### ISSUE TITLE
[Host.AzureServiceBus] Add Azure Message Bus Session Feature

### ISSUE THREAD

**Issue by mpodonyi** [zarusz/SlimMessageBus#49]
Azure Message Bus allows a feature named Message Sessions which guarantees FIFO handling of Messages.
It would be create if there is an easy way to activate this feature in Slim Message Bus.

**Comment by zarusz** [comment]
It could be added to the ASB transport. 

Would something like this satisfy what you need?

Config:
```cs
var bus = MessageBusBuilder.Create()
.Produce<Message>(x => .Topic("topic1").WithModifier((msg, sbMsg) => {
  // Assign some session to that message
  sbMsg.SessionId = "Session1"; // or take from some domain entity msg.CustomerId
}))
.Consume<Message>(x => x.Topic("topic1").SubscriptionName("sub").WithConsumer<MessageConsumer>()
   .EnableSession()) // Enable ASB session for this consumer
. Build();
```

Usage:

```cs
public class MessageConsumer: /*IConsumer<Message>,*/ IServiceBusConsumer<Message> {

   public ServiceBusContext Context { get; set; } // required by the interface  IServiceBusConsumer

   public async Task OnHandle(Message msg, string path) {
      // Context.SessionId
      // Context.MessageId
      var state = await Context.GetSessionState();

      // Modify session state if needed
      // await Context.SetSessionState(state)
   }
}
```

The `IServiceBusConsumer<T>` would extend `IConsumer<T>`.

**Comment by zarusz** [comment]
Sample session consumer from ASB SDK:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md

**Comment by mpodonyi** [comment]
@zarusz Yes that would be create.
Will you implement it or is it already there?

**Comment by mpodonyi** [comment]
Is it also possible to allow to override the following Azure Props:

- 
-       SessionMaxAutoRenewDurationInSeconds
- 
-         SessionMaxConcurrentSessions 
- 
-          SessionMessageWaitTimeoutInSeconds

**Comment by mpodonyi** [comment]
I think it is not so easy to implement as you might think.

In BaseConsumer you are using "Client.RegisterMessageHandler"

for Sessions you would have to use 

"Client.RegisterSessionHandler"

Not sure though.

**Comment by zarusz** [comment]
It would have to implemented (not a current feature). 
Yes, I did recognize the consumer has to use a different API from the ASB client library.

The biggest thing for me is making the consumer aware of the ASB-specific functionality hence the dedicated IServiceBusConsumer along with the ServiceBusContext that would have to be added. I'd need to reflect on that for a bit...

Regarding the `AutoComplete` are you saying you'd like to be able to complete (or abandon) messages manually in some cases?

**Comment by mpodonyi** [comment]
Right now in a self-build implementation, we are using Autocomplete = true for Session based Messages.
This means that if within MessageWaitTimeout no other Message in the session arrives, "Complete" is called automatically.
For Non-Session Messages, we are Using Autocomplete=false and calling Complete ourselves.
Maybe AutoComplete is not required and should go to a default you choose if you handle it within Slim Message Bus.

**Comment by zarusz** [comment]
More info:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

**Comment by zarusz** [comment]
@mpodonyi, I know it's been a while now, but can you help me understand your ASB Session use case:
- do need to choose which specific SessionId to read from OR is it sufficient that the next available SessionId is being picked up by the SMB consumer ([as in here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md#receiving-from-next-available-session)). The consumer choosing what SessionId to join is somewhat harder to integrate (conceptually), but I also feel this is not the main use case. On the other hand, ASB choosing the next available session to be read should be the main use case (like in Kafka broker handing partition assignments).
- do you need to read the session data?
- do you need to write the session data?
- I guess it would be good to add some serialization support for the session data (as part of SMB config)? 

Please let me know.

**Comment by mpodonyi** [comment]
> @mpodonyi, I know it's been a while now, but can you help me understand your ASB Session use case:
> 
> * do need to choose which specific SessionId to read from OR is it sufficient that the next available SessionId is being picked up by the SMB consumer ([as in here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md#receiving-from-next-available-session)). The consumer choosing what SessionId to join is somewhat harder to integrate (conceptually), but I also feel this is not the main use case. On the other hand, ASB choosing the next available session to be read should be the main use case (like in Kafka broker handing partition assignments).

Not really. The sessions is basically assigned round-robin to all consumers and then the session sticks to the consumer as long as something arrives within MessageWaitTimeout. No need to to custom choose Session.

> * do you need to read the session data?
Nope. Except maybe the SessionId which might be useful for adding context to log messages.
> * do you need to write the session data?
Nope
> * I guess it would be good to add some serialization support for the session data (as part of SMB config)?
Not sure?
> 
> Please let me know.

In general we are using sessions to guarantee the ordering of messages. 
Our Producer sets the SessionId.

**Comment by zarusz** [comment]
The feature has been completed. More info here:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_azure_servicebus.md#asb-sessions

Feel free to reopen if more discussion is needed here.
