### ISSUE TITLE
[Question] Is multi-topic (Kafka) consumer supported?

### ISSUE THREAD

**Issue by jpsilvagallino** [zarusz/SlimMessageBus#5]
Hi, congrats on the abstraction library. I have recently come across it, and there is an aspect of it I wanted to check with you guys.

One of Kafka's best practices is to reuse a consumer by subscribing it to multiple topics. Is such set up supported? I see most Topic methods take only a String (e.g., ConsumerBuilder.Topic(string topic)) and not a list of strings, but perhaps it is supported some other way. I recognize beforehand that I haven't dug too deep in the implementation classes still.

Thanks in advance.
Regards,
JP

**Comment by zarusz** [comment]
Hi @jpsilvagallino,

Thanks for the question. Yes, the Kafka transport provider uses one `Confluent.Kafka.Consumer` for all topics (so it reuses the same instance) as long a these topics are part of the same consumer group.

Here is the relevant parts if you need to drill deeper:

https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs#L94 

https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs#L36

https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs#L115

Let me know if you have any more questions.

Cheers

**Comment by jpsilvagallino** [comment]
Hi @zarusz. Thanks for the very quick reply!
All good. I'll start toying around with the project, but it is enough information for now.
Thanks!!
