### ISSUE TITLE
Concurrent message consumers not working

### ISSUE THREAD

**Issue by GMillerVarian** [zarusz/SlimMessageBus#52]
Hi, we can't seem to get messages to be consumed concurrently in our .NET Core 3.1 web app. Here is the code:

**MessageBusBuilder**

```
public class MyMessageBusBuilder
{
    private const int NUM_CONSUMER_INSTANCES = 10;

    public IMessageBus Build(IServiceProvider provider)
    {
        return MessageBusBuilder.Create()
            .PerMessageScopeEnabled(true)
            .Produce<ClientRegisteredMessage>(x => x
                .DefaultTopic("test topic"))
            .Consume<ClientRegisteredMessage>(x => x
                .Topic("test topic")
                .WithConsumer<ClientRegisteredMessageConsumer>()
                .Instances(NUM_CONSUMER_INSTANCES))
            .WithSerializer(new JsonMessageSerializer())
            .WithDependencyResolver(new LookupDependencyResolver(provider.GetRequiredService))
            .WithProviderRedis(new RedisMessageBusSettings("redis connection string"))
            .Build();
    }
}
```

**Startup.cs**

```
public void ConfigureServices(IServiceCollection services)
{
    var messageBusBuilder = provider.GetRequiredService<MyMessageBusBuilder>();

    services
        .AddSingleton<IMessageBus>(messageBusBuilder.Build)
        .AddTransient<ClientRegisteredMessageConsumer>();
}

public void Configure(IApplicationBuilder app)
{
    // Force the singleton SMB instance to be created on app start 
    app.ApplicationServices.GetRequiredService<IMessageBus>();
}
```

At startup, after the "Creating consumers" log entry we see only one "Creating consumer X  for topic Y and message type Z" message logged. We are seeing only one message processed at a time. 

Have looked through the docs and samples including https://zarusz.github.io/SlimMessageBus/docs/intro.html#concurrently-processed-messages, not sure if we are missing something or if there is a bug.

**Comment by GMillerVarian** [comment]
This appears to be an issue with the Redis provider, it is working as expected using the Azure Service Bus provider.

**Comment by zarusz** [comment]
Yes, I think this is isolated to Redis too. Let me do some analysis over the weekend. It might be related to the underlying Redis client.

**Comment by zarusz** [comment]
hey @GMillerVarian, it turns out that the underlying client StackExchange.Redis client does not support concurrent processing by itself, so it worked as if you set `.Instances(1)` for Redis transport.

I have introduced into SMB the ability to parallelize the number of processed messages if `n > 1` in `.Instances(n)`.
The preview is available here:
https://www.nuget.org/packages/SlimMessageBus.Host.Redis/1.14.1-rc1

Let me know if that works for you.

**Comment by GMillerVarian** [comment]
It is working, thank you!
