### ISSUE TITLE
Add support for key in consumer builder

### ISSUE THREAD

**Issue by m786-tech** [zarusz/SlimMessageBus#54]
HI, Is possible to add support for a key in the consumer builder?
I am talking about this line: https://github.com/zarusz/SlimMessageBus/blob/56bc57f8d21e2e7b62401f8938ca2d8211a51f21/src/SlimMessageBus.Host.Kafka/Configs/KafkaMessageBusSettings.cs#L43

Key is helpful when someone want to separate messages by type in one topic, and let consumer listen only on own typed partition, or if  someone need to implement specific consumers per partition key, this could be also consumer per saga.
For example i can define partition key in producer, to be based on message namespace :
```
public static MessageBusBuilder AddProducer<TMessage>(
            this MessageBusBuilder builder, string defaultProduceTopic)
        {

            builder.Produce<TMessage>(x =>
            {
                x.DefaultTopic(defaultProduceTopic);
                x.KeyProvider((request, topic) => Encoding.ASCII.GetBytes(typeof(TMessage).Name));
            });

            return builder;
        }
```
But key sellector on consumer side is missing. Would be nice to extend cconsumer configuration to be able to specify partition key as byte array, or delegate + key deserializer for other types.
I want to implement something like on this image: https://docs.datastax.com/en/kafka/doc/kafka/images/partitionsKafka.png

**Comment by zarusz** [comment]
hi @m786-tech, as far as I know, topics in Kafka are partitioned to increase throughput by partitioning the same/similar types of data on a topic. What goes into a particular partition is derived from a hashing of the key sent upon publish or by providing the index of the partition explicitly (assuming the producer knows how many partitions there are on a topic) - as you observed both are supported in SMB ([here](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_kafka.md#selecting-message-partition-for-topic-producer)).

Now on the consumer side, the Kafka SMB transport uses auto-assignment - Kafka cluster decides what partitions on a topic are assigned to the active consumer group instances and is in charge of revoking assignments over time and to rebalance to maximize throughput. This is the typical setup that allows to quickly balance out if an instance of a consumer group dies or new instances come online - only the Kafka cluster knows about that. In an ideal state, there are more consumer instances than partitions on topic (maximum parallel processing with backup instances waiting in case other consumer instances die). The image that you've linked matches with the above. Secondly, if new partitions were to be added at runtime, then new messages will also be potentially repartitioned and will flow via different partition numbers.

What you're asking for would require a manual assignment to partitions for SMB .
In the underlying Kafka .NET client you need to specify the partition number you would like to read from (sample [here](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_kafka.md#selecting-message-partition-for-topic-producer)), so the partition key does not play a role on the consumer side (unless the ask here is to be able to read the message key like the payload of the message?).

Assuming I understand your ask, I don't see a compelling reason to introduce manual partition assignments on the consumers for SMB. In my mind different types should flow through different types of topic. Unless you're asking for filtering of messages based on message type (see #32 and #33) or simply being able to read the key by the consumer?

**Comment by m786-tech** [comment]
Hi Zarusz, yes , i want to filter out messages based on types. Similiar as asked in #32. Partitions were designed to keep related messages (related by key) together in same partition, so my first choise was to use parttioning by key. If this is not a way to go, do you have another way or plan how to achieve it?

**Comment by zarusz** [comment]
I guess I can look into doing #33 and #32 here soon. That should give you what you need.

If so please close this one and let's move to the other issue.

**Comment by m786-tech** [comment]
ok. thanks.
