### ISSUE TITLE
Using Auto Discovery on different Assemblies 

### ISSUE THREAD

**Issue by arnoldsi-vii** [zarusz/SlimMessageBus#62]
Hi,
I saw the Do method to auto discover producers and consumers. Is it possible to use it multiple time? For example if I have different project within the solution and I want to register the producers and consumers there.

Thanks

**Comment by zarusz** [comment]
Hi @arnoldsi-vii , off the top of my head I believe it should be possible yes. I'd say just repeat that discovery code inside the `.Do()` multiple times for each assembly. 

Do you need a sample for this?

**Comment by arnoldsi-vii** [comment]
@zarusz Thank you for your answer. I haven't explored the source code, wouldn't .Do() create a new builder each time I run it?
It could be nice to have extension similar to fluentValidation:
`services.AddValidatorsFromAssembly(Assembly.GetExecutingAssembly());`

I'll check the source, but if you can save me some time and let me know if .Do() will keep the original builder and add more producers and consumers to it.

Thank you very much

**Comment by arnoldsi-vii** [comment]
There is a "not so clean" solution:
In Startup.cs Create Messagebus in constructor (which can also impact startup, can be optimized by Lazy):
```
public MessageBusBuilder MessageBusBuilder { get; }
        public Startup()
        {
            MessageBusBuilder = MessageBusBuilder.Create();

        }
```

Then pass `MessageBusBuilder` to other projects DI and run the `.Do()` method. 
I don't a fan of that approach, but it can work as temporary solution.
I'll appreciate your ideas to this issues

**Comment by zarusz** [comment]
You can chain as many `mbb.Do()` as you want - it will add to the existing SMB configuration objects being built.
The `MessageBusBuilder.Create();` is actually pretty light. The actual heavy build happened in `mbb.Create()` where the whole bus is instantiated.

The example with `AddValidatorsFromAssembly` for fluentValidation only scans (via reflection) the assembly and then registers this implementation with the MsDependencyInjection. I was thinking about adding such convenience to the SlimMessageBus.Host.MsDependencyInjection plugin, but never got to it. If this helps I could add this with the next release (it's actually simple).  Now as I understand that alone won't solve your problem as you want to also get ahold of the `MessageBusBuilder` to keep adding to it in your logical modules, right?

Your workaround seems valid for now, but I agree it would be way nicer if the library give some support for such modularization.

```cs
// SlimMessageBus.Host nuget
interface IMessageBusConfiguration {

  void Configure(MessageBusBuilder mbb);
}
```

```cs
// in one of your modules / layers
class MyModuleBusConfiguration : IMessageBusConfiguration {

  public MyModuleBusConfiguration(/* injected dependencies by DI eg options */)

  public voud Configure (MessageBusBuilder mbb) {
    // configures the bus
     mbb
        .Consume<Message>(x =>x.Topic(...).WithConsumer<TMessageConsumer>())
        .Produce<AnotherMessage>(...);
   }
}

```cs
// Startup.cs


services.AddSlimMessageBus((mbb, svp) => {
  mbb
     .WithSerialization(...)
     .WithKafkaProvider(...)
});

services.AddSlimMessageBusConfigurationFromAssembly(...) // scans for IMessageBusConfiguration  implementations
services.AddConsumersFromAssembly(...) // scans for IConsumer<T> or IHandler<> implementations

```

Is that what you're after?

**Comment by arnoldsi-vii** [comment]
Hi,
Thank you very much for your response. 
It can be great addition to the library. Starting with simple solution of extending MsDependencyInjection and maybe in a future add the option to set dynamic configurations to allow developers to create stand alone modules

**Comment by zarusz** [comment]
@arnoldsi-vii  I went ahead and baked in the proposed prototype and released an RC release. 
If could give it a try, check the API if it's optimal and if that's what could solve your use case?

The docs (still very rudimentary) are here:
https://github.com/zarusz/SlimMessageBus/blob/feature/Using_Auto_Discovery_on_different_Assemblies_%2362/docs/intro.md#msdependencyinjection

I still need to test this a bit more. 

https://www.nuget.org/packages/SlimMessageBus.Host.AspNetCore/1.6.4-rc1
https://www.nuget.org/packages/SlimMessageBus.Host.MsDependencyInjection/1.6.4-rc1

**Comment by arnoldsi-vii** [comment]
@zarusz AWESOME! I'll check it out

**Comment by zarusz** [comment]
@arnoldsi-vii  any feedback, please? 
I am considering merging it soon.

**Comment by arnoldsi-vii** [comment]
Hi @zarusz, We run this rc1 on small production service today. I will let you know ASAP

**Comment by arnoldsi-vii** [comment]
Hi @zarusz ,
We did some tests in production, we haven't found any issues, but those tests were on small services. 
We will run more tests on this in our staging env.

**Comment by zarusz** [comment]
Hi @arnoldsi-vii , thanks for getting back to me and reporting.
I am mostly interested if conceptually what was added fulfil your application needs?

Stability-wise, I believe it should be good.

**Comment by arnoldsi-vii** [comment]
@zarusz I really loved the idea of separation and code organization.
It allowed dry and clear approach for using the library

**Comment by zarusz** [comment]
Glad to hear that. I will incorporate into the main version. Cheers.

**Comment by arnoldsi-vii** [comment]
Hi @zarusz any updates when this is going to be added to the release?

**Comment by zarusz** [comment]
I planned for this weekend, however ended up working on another feature.  Will target next weekend.

**Comment by zarusz** [comment]
This is now released therefore closing. Feel free to reopen if any issues.
