### ISSUE TITLE
[Host.RabbitMQ] Missing RabbitMQ Implementation

### ISSUE THREAD

**Issue by fahadash** [zarusz/SlimMessageBus#67]
RabbitMQ Implementation seems to be missing. We would love to have that.

**Comment by zarusz** [comment]
I agree 👍. Do you want (have time) to contribute ? :)

**Comment by hatzhang** [comment]
How is it going now?

**Comment by zarusz** [comment]
Nothing has been done yet that I am aware of. Let me know if you're willing to work on the implementation, otherwise I will start this.

**Comment by zarusz** [comment]
Will use this client to implement the Rabbit transport:
https://www.nuget.org/packages/RabbitMQ.Client

**Comment by zarusz** [comment]
The RebbitMQ transport is available:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_rabbitmq.md

The preview version is available:
https://www.nuget.org/packages/SlimMessageBus.Host.RabbitMQ

Feedback is welcome!
