### ISSUE TITLE
Migrate to new Azure.Messaging.ServiceBus library

### ISSUE THREAD

**Issue by vaclavholusa** [zarusz/SlimMessageBus#70]
Hello, Microsoft has officially deprecated [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) in favor of  [Azure.Messaging.ServiceBus ](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/)

The ASB Transport layer should be roworked to use this newer library. Migration guide available [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md)

**Comment by zarusz** [comment]
It looks like the migration will be quite easy. I already made some progress on this. 
Perhaps within a few days, I might release the first version.

**Comment by zarusz** [comment]
I have it almost done. Need to test this a bit more and update the documentation.

**Comment by vaclavholusa** [comment]
Well done! Can't wait for a release :)

**Comment by zarusz** [comment]
Thanks, it's released now:

https://github.com/zarusz/SlimMessageBus/releases/tag/Host.Transport-1.15.5

**Comment by zarusz** [comment]
And thanks @vaclavholusa  for raising the lib deprecation to my attention!
