### ISSUE TITLE
[Host.Serialization.Google.Protobuf]  Google Protobuf Serialization

### ISSUE THREAD

**Issue by AChehre** [zarusz/SlimMessageBus#91]
We need to serialize/de-serialize google protobuf messages.
Do we have implementation?

**Comment by zarusz** [comment]
Hello, no, not yet. Do you want to contribute a PR?

**Comment by AChehre** [comment]
> Hello, no, not yet. Do you want to contribute a PR?

sure

**Comment by zarusz** [comment]
The feature has bee build & released as part of #93
