### ISSUE TITLE
[Host.FluentValidation] Based on the new interceptor capability implement message validation when Publish/Send on the memory bus

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#94]
With the [Interceptor](https://github.com/zarusz/SlimMessageBus/blob/master/docs/intro.md#interceptors) feature added recently, we could build a FluentValidaion plugin that would allow the users to easily add message validation into SMB.

https://docs.fluentvalidation.net/en/latest/

**Comment by baoduy** [comment]
Hi @zarusz  .Net itself also has Validator. I think we should provide both Fluent validation and this native validation.
I could able to contribute the code. However, would like to discuss with you the project naming first. :)

Thanks
Steven

**Comment by zarusz** [comment]
Hi @baoduy , that sounds nice. Do you refer to the [ASP.NET model validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0) or something else? 

In terms of naming, I planned to call the FluentValidation one simply `SlimMessageBus.Host.FluentValidation`. If there would be more validation plugins perhaps, we could name it ` SlimMessageBus.Host.Validation.FluentValidation`

**Comment by baoduy** [comment]
Hi @zarusz It would be more validation plugins in the future. So We shall go with `SlimMessageBus.Host.Validation.FluentValidation` :)
